[[blog]]
id = 1
name = ""
description = ""
url = "https://yoururl.com/"
tone = "Passionate, informative, authentic, community-focused, and future-oriented."
keywords = ""

[[blog]]
id = 2
name = ""
description = ""
url = "https://yoururl.com/"
tone = "Straightforward, community-focused, inspiring. Use words that a 36-years old nomad and indie hacker would use."
keywords = ""
